package modelManifiesto.bc.entidad;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 04 11:45:24 ECT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FilialDetalleImpl extends Entidad {
    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
        //Id refresh
        if (operation == DML_INSERT)
            setAttribute(IDFILIALDETALLE, getUltimoId());
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFilialDetalle,
        IdFilial,
        IdLibroDireccion,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        Filial,
        LibroDireccion;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDFILIALDETALLE = AttributesEnum.IdFilialDetalle.index();
    public static final int IDFILIAL = AttributesEnum.IdFilial.index();
    public static final int IDLIBRODIRECCION = AttributesEnum.IdLibroDireccion.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int FILIAL = AttributesEnum.Filial.index();
    public static final int LIBRODIRECCION = AttributesEnum.LibroDireccion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FilialDetalleImpl() {
        super();
        setNombreBundle("modelManifiesto.ModelManifiestoBundle");
    }

    /**
     * @param idFilialDetalle key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idFilialDetalle) {
        return new Key(new Object[] { idFilialDetalle });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("modelManifiesto.bc.entidad.FilialDetalle");
    }


}

