package modelManifiesto.bc.entidad;

import model.bc.Entidad;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 20 21:17:07 ECT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LibroDireccionImpl extends Entidad {
    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        setAttribute(ESTADO, "X");
        super.remove();
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdLibroDireccion,
        Indice,
        IndiceSecundario,
        IdentificacionFiscal,
        Nombre,
        Tipo,
        Correo,
        Estado,
        Usuario,
        UsuarioFecha,
        UsuarioPrograma,
        AerolineaUsuario,
        FilialDetalle;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDLIBRODIRECCION = AttributesEnum.IdLibroDireccion.index();
    public static final int INDICE = AttributesEnum.Indice.index();
    public static final int INDICESECUNDARIO = AttributesEnum.IndiceSecundario.index();
    public static final int IDENTIFICACIONFISCAL = AttributesEnum.IdentificacionFiscal.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int TIPO = AttributesEnum.Tipo.index();
    public static final int CORREO = AttributesEnum.Correo.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();
    public static final int USUARIOFECHA = AttributesEnum.UsuarioFecha.index();
    public static final int USUARIOPROGRAMA = AttributesEnum.UsuarioPrograma.index();
    public static final int AEROLINEAUSUARIO = AttributesEnum.AerolineaUsuario.index();
    public static final int FILIALDETALLE = AttributesEnum.FilialDetalle.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LibroDireccionImpl() {
        super();
    }

    /**
     * @param idLibroDireccion key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer idLibroDireccion) {
        return new Key(new Object[] { idLibroDireccion });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("modelManifiesto.bc.entidad.LibroDireccion");
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        if (operation == DML_DELETE) {
            noBorrar(AEROLINEAUSUARIO);            
            operation = DML_UPDATE;
        }

        super.doDML(operation, e);
        //Id refresh
        if (operation == DML_INSERT)
            setAttribute(IDLIBRODIRECCION, getUltimoId());
    }
}

