package modelManifiesto.bc.vista.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 08 16:03:04 ECT 2024
// ---------------------------------------------------------------------
public interface FilialView extends ViewObject {
    void ejecutarByIndice(int idManifiesto);
}

