package modelManifiesto.bc.vista.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 07 02:37:13 ECT 2024
// ---------------------------------------------------------------------
public interface LibroDireccionView extends ViewObject {
    String exportarExcel(String param, String param2, String param3, String param4);
}

