package modelManifiesto.bc.vistaNoDML;

import model.bc.VistaObjeto;

import modelManifiesto.bc.vistaNoDML.common.CatalogoFilialesViewNoDML;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 04 11:23:05 ECT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CatalogoFilialesViewNoDMLImpl extends VistaObjeto implements CatalogoFilialesViewNoDML {

    /**
     * This is the default constructor (do not remove).
     */
    public CatalogoFilialesViewNoDMLImpl() {
        super();
    }

    /**
     * Metodo para listar el catalogo para busqueda en manifiesto.
     *
     * @param idFilial
     */
    public void ejecutarByManifiesto(int idFilial) {
        ViewCriteria vc = this.getViewCriteriaManager().getViewCriteria("CatalogoFilialesManifiestoViewNoDMLCriteria");
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_id_filial", idFilial);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }

    /**
     * Metodo para listar el catalogo para busqueda en preliquidacion.
     *
     * @param idFilial
     */
    public void ejecutarByPreliquidacion(int idFilial) {
        ViewCriteria vc =
            this.getViewCriteriaManager().getViewCriteria("CatalogoFilialesPreliquidacionViewNoDMLCriteria");
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_id_filial", idFilial);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }
}