package modelManifiesto.bc.vistaNoDML;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

import model.bc.VistaObjeto;

import modelManifiesto.bc.vistaNoDML.common.ManifiestoSumatoriasViewNoDML;

import modelManifiesto.utilidades.GenerarSqlManifiesto;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 09 14:54:41 ECT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ManifiestoSumatoriasViewNoDMLImpl extends VistaObjeto implements ManifiestoSumatoriasViewNoDML {
    /**
     * This is the default constructor (do not remove).
     */
    public ManifiestoSumatoriasViewNoDMLImpl() {
        super();
    }
    
    
    /**
     * Metodo para iniciar la lista sin consultas previas.
     *
     */
    public void inicioVacio() {
        String sqlOriginal = this.getQuery();
        
        String sql = sqlOriginal + " where id_manifiesto = -1";

        this.setQuery(sql);        
        this.executeQuery();

        this.setQuery(sqlOriginal);
    }
    
    /**
     * Metodo para hacer una consulta extendida de los cierres de vuelo.
     * @param idUsuario
     * @param indiceAerolinea
     * @param indiceAeropuertoOrigen
     * @param indiceAeropuertoDestino
     * @param indiceAeronave
     * @param noVuelo
     * @param fechaInicio
     * @param fechaFin
     * @param idManifiesto
     * @param estado    (estado)Estado del manifiesto y procesos internos JDE
     * @param tipoVuelo    (tipo)Tipo de vuelo I=vuelo internacional, N=Vuelo Nacional
     * @param tipoObservacion   (cancelado)Si el vuelo ha sido cancelado con la N = Normal y C=Cancelado 
     */
    public void ejecutarConsultaExtendida(int idUsuario, int indiceAerolinea, int indiceAeropuertoOrigen,
                                          int indiceAeropuertoDestino, int indiceAeronave, String noVuelo,
                                          String fechaInicio, String fechaFin, String idManifiesto, String estado,
                                          String tipoVuelo, String tipoObservacion) {
        String sqlOriginal = this.getQuery();
        String sql = GenerarSqlManifiesto.generarSQLExtendido(sqlOriginal, idUsuario, indiceAerolinea, indiceAeropuertoOrigen,
                                            indiceAeropuertoDestino, indiceAeronave, noVuelo, fechaInicio, fechaFin,
                                            idManifiesto, estado, tipoVuelo, tipoObservacion);        
        this.setQuery(sql);        
        this.executeQuery();
        this.setQuery(sqlOriginal);
    }
}

