package modelManifiesto.bc.vistaNoDML.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 04 16:35:12 ECT 2024
// ---------------------------------------------------------------------
public interface CatalogoFilialesViewNoDML extends ViewObject {
    void ejecutarByManifiesto(int idFilial);

    void ejecutarByPreliquidacion(int idFilial);
}

