package modelManifiesto.bc.vistaNoDML.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 14 18:55:30 ECT 2022
// ---------------------------------------------------------------------
public interface ManifiestoViewNoDML extends ViewObject {

    void cargarValoresDefaultBusqueda01(String idUsuario);

    void cargarValoresDefaultBusqueda02(String idUsuario);

    void ejecutarConsulta(int idUsuario, int indiceAerolinea, int indiceAeropuertoOrigen, int indiceAeropuertoDestino,
                          int indiceAeronave, String noVuelo, String fechaInicio, String fechaFin);

    void ejecutarConsultaErrorJDE();

    void inicioVacio();

    void ejecutarConsultaPreliquidacion(int idUsuario, int indiceAerolinea, int indiceAeropuertoOrigen,
                                        int indiceAeropuertoDestino, int indiceAeronave, String noVuelo,
                                        String fechaInicio, String fechaFin);

    void inicioVacioPreliquidacion();
}
