package modelManifiesto.bc.vistaNoDML.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 09 15:02:31 ECT 2023
// ---------------------------------------------------------------------
public interface ManifiestoSumatoriasViewNoDML extends ViewObject {
    void ejecutarConsultaExtendida(int idUsuario, int indiceAerolinea, int indiceAeropuertoOrigen,
                                   int indiceAeropuertoDestino, int indiceAeronave, String noVuelo, String fechaInicio,
                                   String fechaFin, String idManifiesto, String estado, String tipoVuelo,
                                   String tipoObservacion);

    void inicioVacio();
}

