package modelManifiesto.bc.vistaNoDML.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 24 00:33:10 ECT 2022
// ---------------------------------------------------------------------
public interface UsuarioAsignadoViewNoDML extends ViewObject {
    void ejecutarByIndice(int idUsuario);
}

