package modelManifiesto.bc.vista;

import model.bc.VistaObjeto;

import modelManifiesto.bc.vista.common.FilialView;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 08 16:01:08 ECT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FilialViewImpl extends VistaObjeto implements FilialView {
    /**
     * This is the default constructor (do not remove).
     */
    public FilialViewImpl() {        super();
    }

    /**
     * Metodo para ejecutar por idUsuario.
     *
     * @param idManifiesto
     *
     */
    public void ejecutarByIndice(int idManifiesto) {
        ViewCriteria vc = this.getViewCriteriaManager().getViewCriteria("FilialViewCriteria");
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_IdFilial", idManifiesto);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }
}

