package modelManifiesto.bc.vista;


import model.bc.VistaObjeto;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 07 02:36:26 ECT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LibroDireccionViewImpl extends VistaObjeto {
    /**
     * This is the default constructor (do not remove).
     */
    public LibroDireccionViewImpl() {
        super();
    }
}

