package modelManifiesto.bc.vista;

import model.bc.VistaObjeto;

import modelManifiesto.bc.vista.common.ManifiestoView;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 22 09:25:13 ECT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ManifiestoViewImpl extends VistaObjeto implements ManifiestoView {
    /**
     * This is the default constructor (do not remove).
     */
    public ManifiestoViewImpl() {
        super();
    }

    /**
     * Metodo para ejecutar por idUsuario.
     *
     * @param idManifiesto
     *
     */
    public void ejecutarByIndice(int idManifiesto) {
        ViewCriteria vc = this.getViewCriteriaManager().getViewCriteria("ManifiestoViewCriteriaByIndice");
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("v_IdManifiesto", idManifiesto);
        this.applyViewCriteria(vc, false);
        this.executeQuery();
        this.setApplyViewCriteriaName(null);
    }
}

