package modelManifiesto.bc.vista;

import model.bc.VistaObjeto;

import modelManifiesto.bc.vista.common.ManifiestoView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 22 12:13:08 ECT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ManifiestoInsertViewImpl extends VistaObjeto  {
    /**
     * This is the default constructor (do not remove).
     */
    public ManifiestoInsertViewImpl() {
    }
}

