CALL "DATA".PK_JDE_PEDIDOS_WS.SP_CREAR_ORDEN_VENTA(:P_UNIDADNEGOCIO, :P_CODIGOMONEDA, :P_FECHAORDEN, :P_FECHAPEDIDO, :P_ITEMID, :P_CATIDADORDEN, :P_ENVIARID, :P_TIPOPROCESAMIENTO, :P_VERSIONPROCESAMIENTO, :P_VENDIDOID, ?);

